#
# Author: Jiaqing "Lance" Wang <jiaqing.wang@sjtu.edu.cn>
# Shanghai Jiao Tong University, The Nezha Lab
# Key Laboratory of Polar Ecosystem and Climate Change
# State Key Laboratory of Submarine Geoscience
#
# Request
float64 number
float64 amplitude
float64 period
float64 direction_x
float64 direction_y
float64 scale
float64 angle
float64 steepness
---
# Response
bool success
string message


